spring.application.name=technical

# API Versioning
application.api.base-path=/api/v1

# JWT Configuration
application.security.jwt.secret-key=843567893696976453275974432697R634976R738467TR678T34865R6834R8763T478378637664538745673865783678548735687R3
application.security.jwt.expiration=86400000

# ===============================
# PostgreSQL Database Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://ep-green-mountain-atptphh9-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_P6irK8fseRNb
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true